/*! jQuery v1.7.2 jquery.com | jquery.org/license */
(function () {
    $(function () { linerFloat(); quickNav(); navChange(); var focus = new picScroll($(".lv-ban-tab"), $(".lv-ban-imgs")); banSmall(); replaceLink(); tripHotUp(); }); function navChange() { var lvSiderNav = $(".lv-sidernav"), hover = false, attrX = [], timer1 = null, timer2 = null, timer3 = null; lvSiderNav.hover(function () { timer1 = setTimeout(function () { hover = true; }, 300); }, function () { $(this).find(".lv-sidernav-list").removeClass("active"); hover = false; clearTimeout(timer1); }); $(".lv-sidernav-list").hover(function (e) { var me = $(this), X = e.pageX, l = attrX.length, oldX = attrX[l - 5]; if (hover == true && X <= oldX + 5) { hoverNav(me); clearTimeout(timer3); attrX = []; } else { clearTimeout(timer3); var me = $(this); timer2 = setTimeout(function () { hoverNav(me); }, 500); } }, function () { var me = $(this); timer3 = clearTimeout(function () { $(this).removeClass("active"); }, 300); clearTimeout(timer2); }); lvSiderNav.mousemove(function (e) { var X = e.pageX; attrX.push(X); }); function hoverNav(elm) { elm.addClass("active").siblings().removeClass("active"); }; }
    function replaceLink() { $(document).on('click', 'li', function () { var me = $(this), parLink = me.parent().next(); if (me.attr('parenttype') == 'picWeek') { if (me.index() == 1) { parLink.attr('href', 'http://www.lvmama.com/around/'); } else { parLink.attr('href', 'http://www.lvmama.com/freetour/'); } } }); }
    function picScroll(tabbox, picBox) {
        var index = 0, tabs, pics = picBox.find("li"), l = pics.length, Timer = null; clearTimeout(Timer); autoPlay(); pics.each(function (e) { e == 0 ? tabbox.append('<li class="active"></li>') : tabbox.append("<li></li>"); }); tabs = tabbox.find("li"); tabs.each(function (e) { var me = $(this); me.hover(function () { index = e;  clearTimeout(Timer); }); }); picBox.parents('.lv-ban-wrap').hover(function () { clearTimeout(Timer); }, function () { clearTimeout(Timer); autoPlay(); }); function autoPlay() {
            var img = new Image(); var imgs = pics.eq(index).find('img'); var imgSrc = imgs.size() > 0 ? (imgs.attr('src') || imgs.attr('to') || imgs.attr('js_to')) : null; if (!imgSrc) { clearTimeout(Timer); setTimeout(autoPlay, 1000); return; }
            img.onload = function () { Timer = setTimeout(function () { index = index >= (l - 1) ? 0 : index + 1; autoPlay(); }, 5000); }
            img.src = imgSrc;
        }; 
    }
    function setImg(obj, index) { var indexImg = obj.eq(index).find('img'); var js_to = indexImg.attr('js_to'); var js_sc = indexImg.attr('js_sc'); var to = indexImg.attr('to'); var to_sc = indexImg.attr('to_sc'); var trd = indexImg.attr('to_trd'); var trdU, img; ((trd != 'null') && (trd != undefined)) && (trdU = new Image().src = trd); js_to && indexImg.attr('src', js_to).removeAttr('js_to'); js_sc && (img = new Image().src = js_sc, indexImg.removeAttr('js_sc')); to && indexImg.attr('src', to).removeAttr('to'); to_sc && (img = new Image().src = to_sc, indexImg.removeAttr('to_sc')); }; function banSmall() {
        var $banSmallBox = $('.lv-banSmallBox'), banSmall = $banSmallBox.find('ul'), isPlay = false, pageIndex = 0, banSmallLi = banSmall.find('li'), timer = null; auto(); $('.btn-banSmall').each(function () { var me = $(this); me.click(function () { var $meIndex = me.index(); num($meIndex); }); }); $banSmallBox.hover(function () { clearTimeout(timer); }, function () { auto(); }); function num(index) { if (isPlay) return; isPlay = true; pageIndex = index > 0 ? pageIndex + 1 : pageIndex - 1; if (pageIndex < 0) { banSmall.css('marginTop', -726); pageIndex = 1; banSmallPlay(1); for (var j = 3; j < 6; j++) { setImg(banSmallLi, j); } } else if (pageIndex > 1) { pageIndex = 0; banSmallPlay(2); for (var j = 0; j < 3; j++) { setImg(banSmallLi, j); } } else { banSmallPlay(pageIndex); for (var j = pageIndex * 3; j < pageIndex * 3 + 3; j++) { setImg(banSmallLi, j); } } }
        function banSmallPlay(i) { banSmall.stop(true, true).animate({ marginTop: -363 * i }, 500, function () { isPlay = false; i == 2 && banSmall.css('marginTop', 0); }); }
        function auto() { timer = setTimeout(function () { num(1); auto(); }, 7000); }
    }
    function quickNav() {
        var sideNavBox = $('.nav-right'), sideNav = sideNavBox.find('li'); subScroll = $('.public-box'), body = $('html,body'), doc = $(document), docTop = doc.scrollTop(), w = $(window).width(), lastTop = subScroll.eq(4).offset().top, liner_float_l = $('.liner_float_l'); scrollFunc(); sideNavShow(); mouseScroll(document); $(window).resize(function () { w = $(window).width(); sideNavShow(); }); sideNav.each(function (e) { var me = $(this); me.click(function () { body.stop(true, true).animate({ scrollTop: subScroll.eq(e).offset().top - (me.offset().top - $(window).scrollTop()) + 30 + 'px' }, 300, function () { changeNav(e, sideNav); }); }); }); function changeNav(i, nav) { nav.eq(i).addClass('active').siblings().removeClass('active'); }
        function sideNavShow() { if (w > 1280) { if (docTop > 500) { sideNavBox.show().css({ top: '100px' }); if (docTop >= lastTop - 100) sideNavBox.css('top', lastTop - docTop - 100); } else if (docTop >= lastTop) { } else {  liner_float_l.fadeOut("fast"); } } else {  liner_float_l.hide(); } }; function mouseScroll(elm) {
            if (elm.addEventListener) { elm.addEventListener('DOMMouseScroll', scrollFunc, false); }
            window.onmousewheel = elm.onmousewheel = window.onscroll = scrollFunc;
        }; function scrollFunc() { docTop = doc.scrollTop(); sideNavShow(); subScroll.each(function (e) { if (docTop >= subScroll.eq(e).offset().top - $(window).height() / 4 - 100) { changeNav(e, sideNav); } }); };
    }
    function tripHotUp() { var timer = null, lcHotBox = $('.lvyoubao-info'); clearInterval(timer); lyb_autoPlay(); lcHotBox.hover(function () { clearInterval(timer); }, function () { lyb_autoPlay(); }); function lyb_autoPlay() { timer = setInterval(function () { getLcHotHeight(); }, 2000); } }; function getLcHotHeight() { var lc_hot = $('.lvyoubao-info li'); var h = -lc_hot.first().outerHeight(); var first_html = lc_hot.first().html(); lc_hot.first().animate({ "margin-top": h }, 500, function () { lc_hot.last().after("<li>" + first_html + "</li>"); $(this).remove(); }); }; function linerFloat() { var html = '<div class="liner_float_l"><a class="liner_float_b"  target="_blank" href="http://www.lvmama.com/zt/promo/wenminglvyou/"></a><a class="liner_float_s" target="_blank" href="http://www.lvmama.com/zt/promo/wenminglvyou/"></a><span class="liner_float_close" title="关闭"></span></div>'; $('body').append(html); $('.liner_float_close').live('click', function () { $(this).parent('.liner_float_l').remove(); }); var $liner_float_l = $('.liner_float_l'), $liner_float_b = $('.liner_float_b'), $liner_float_s = $('.liner_float_s'); $liner_float_l.hover(function () { mousein(); }, function () { mouseout(); }); function mouseout() { $liner_float_s.stop(true).animate({ 'width': 0 }, 400, function () { $liner_float_s.hide(); $liner_float_l.css({ 'width': 45 }); }); }; function mousein() { $liner_float_l.css({ 'width': 186 }); $liner_float_s.show().stop(true).animate({ 'width': 167 }, 400); }; }
})(jQuery);
