//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace DataModel
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class hackthonEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new hackthonEntities object using the connection string found in the 'hackthonEntities' section of the application configuration file.
        /// </summary>
        public hackthonEntities() : base("name=hackthonEntities", "hackthonEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new hackthonEntities object.
        /// </summary>
        public hackthonEntities(string connectionString) : base(connectionString, "hackthonEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new hackthonEntities object.
        /// </summary>
        public hackthonEntities(EntityConnection connection) : base(connection, "hackthonEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<comment> comments
        {
            get
            {
                if ((_comments == null))
                {
                    _comments = base.CreateObjectSet<comment>("comments");
                }
                return _comments;
            }
        }
        private ObjectSet<comment> _comments;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<diary> diaries
        {
            get
            {
                if ((_diaries == null))
                {
                    _diaries = base.CreateObjectSet<diary>("diaries");
                }
                return _diaries;
            }
        }
        private ObjectSet<diary> _diaries;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<order> orders
        {
            get
            {
                if ((_orders == null))
                {
                    _orders = base.CreateObjectSet<order>("orders");
                }
                return _orders;
            }
        }
        private ObjectSet<order> _orders;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<product> products
        {
            get
            {
                if ((_products == null))
                {
                    _products = base.CreateObjectSet<product>("products");
                }
                return _products;
            }
        }
        private ObjectSet<product> _products;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<user> users
        {
            get
            {
                if ((_users == null))
                {
                    _users = base.CreateObjectSet<user>("users");
                }
                return _users;
            }
        }
        private ObjectSet<user> _users;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the comments EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocomments(comment comment)
        {
            base.AddObject("comments", comment);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the diaries EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTodiaries(diary diary)
        {
            base.AddObject("diaries", diary);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the orders EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToorders(order order)
        {
            base.AddObject("orders", order);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the products EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToproducts(product product)
        {
            base.AddObject("products", product);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTousers(user user)
        {
            base.AddObject("users", user);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="hackthonModel", Name="comment")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class comment : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new comment object.
        /// </summary>
        /// <param name="diaryID">Initial value of the diaryID property.</param>
        public static comment Createcomment(global::System.Int32 diaryID)
        {
            comment comment = new comment();
            comment.diaryID = diaryID;
            return comment;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diaryID
        {
            get
            {
                return _diaryID;
            }
            set
            {
                if (_diaryID != value)
                {
                    OndiaryIDChanging(value);
                    ReportPropertyChanging("diaryID");
                    _diaryID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diaryID");
                    OndiaryIDChanged();
                }
            }
        }
        private global::System.Int32 _diaryID;
        partial void OndiaryIDChanging(global::System.Int32 value);
        partial void OndiaryIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> commentID
        {
            get
            {
                return _commentID;
            }
            set
            {
                OncommentIDChanging(value);
                ReportPropertyChanging("commentID");
                _commentID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("commentID");
                OncommentIDChanged();
            }
        }
        private Nullable<global::System.Int32> _commentID;
        partial void OncommentIDChanging(Nullable<global::System.Int32> value);
        partial void OncommentIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String content
        {
            get
            {
                return _content;
            }
            set
            {
                OncontentChanging(value);
                ReportPropertyChanging("content");
                _content = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("content");
                OncontentChanged();
            }
        }
        private global::System.String _content;
        partial void OncontentChanging(global::System.String value);
        partial void OncontentChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="hackthonModel", Name="diary")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class diary : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new diary object.
        /// </summary>
        /// <param name="diaryID">Initial value of the diaryID property.</param>
        public static diary Creatediary(global::System.Int32 diaryID)
        {
            diary diary = new diary();
            diary.diaryID = diaryID;
            return diary;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diaryID
        {
            get
            {
                return _diaryID;
            }
            set
            {
                if (_diaryID != value)
                {
                    OndiaryIDChanging(value);
                    ReportPropertyChanging("diaryID");
                    _diaryID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diaryID");
                    OndiaryIDChanged();
                }
            }
        }
        private global::System.Int32 _diaryID;
        partial void OndiaryIDChanging(global::System.Int32 value);
        partial void OndiaryIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> userID
        {
            get
            {
                return _userID;
            }
            set
            {
                OnuserIDChanging(value);
                ReportPropertyChanging("userID");
                _userID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("userID");
                OnuserIDChanged();
            }
        }
        private Nullable<global::System.Int32> _userID;
        partial void OnuserIDChanging(Nullable<global::System.Int32> value);
        partial void OnuserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String title
        {
            get
            {
                return _title;
            }
            set
            {
                OntitleChanging(value);
                ReportPropertyChanging("title");
                _title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("title");
                OntitleChanged();
            }
        }
        private global::System.String _title;
        partial void OntitleChanging(global::System.String value);
        partial void OntitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String content
        {
            get
            {
                return _content;
            }
            set
            {
                OncontentChanging(value);
                ReportPropertyChanging("content");
                _content = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("content");
                OncontentChanged();
            }
        }
        private global::System.String _content;
        partial void OncontentChanging(global::System.String value);
        partial void OncontentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String tag
        {
            get
            {
                return _tag;
            }
            set
            {
                OntagChanging(value);
                ReportPropertyChanging("tag");
                _tag = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("tag");
                OntagChanged();
            }
        }
        private global::System.String _tag;
        partial void OntagChanging(global::System.String value);
        partial void OntagChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> publishTime
        {
            get
            {
                return _publishTime;
            }
            set
            {
                OnpublishTimeChanging(value);
                ReportPropertyChanging("publishTime");
                _publishTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("publishTime");
                OnpublishTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _publishTime;
        partial void OnpublishTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnpublishTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> readTimes
        {
            get
            {
                return _readTimes;
            }
            set
            {
                OnreadTimesChanging(value);
                ReportPropertyChanging("readTimes");
                _readTimes = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("readTimes");
                OnreadTimesChanged();
            }
        }
        private Nullable<global::System.Int32> _readTimes;
        partial void OnreadTimesChanging(Nullable<global::System.Int32> value);
        partial void OnreadTimesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> buyTimes
        {
            get
            {
                return _buyTimes;
            }
            set
            {
                OnbuyTimesChanging(value);
                ReportPropertyChanging("buyTimes");
                _buyTimes = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("buyTimes");
                OnbuyTimesChanged();
            }
        }
        private Nullable<global::System.Int32> _buyTimes;
        partial void OnbuyTimesChanging(Nullable<global::System.Int32> value);
        partial void OnbuyTimesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> likeTimes
        {
            get
            {
                return _likeTimes;
            }
            set
            {
                OnlikeTimesChanging(value);
                ReportPropertyChanging("likeTimes");
                _likeTimes = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("likeTimes");
                OnlikeTimesChanged();
            }
        }
        private Nullable<global::System.Int32> _likeTimes;
        partial void OnlikeTimesChanging(Nullable<global::System.Int32> value);
        partial void OnlikeTimesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> commentTimes
        {
            get
            {
                return _commentTimes;
            }
            set
            {
                OncommentTimesChanging(value);
                ReportPropertyChanging("commentTimes");
                _commentTimes = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("commentTimes");
                OncommentTimesChanged();
            }
        }
        private Nullable<global::System.Int32> _commentTimes;
        partial void OncommentTimesChanging(Nullable<global::System.Int32> value);
        partial void OncommentTimesChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="hackthonModel", Name="order")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class order : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new order object.
        /// </summary>
        /// <param name="orderID">Initial value of the orderID property.</param>
        public static order Createorder(global::System.Int32 orderID)
        {
            order order = new order();
            order.orderID = orderID;
            return order;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 orderID
        {
            get
            {
                return _orderID;
            }
            set
            {
                if (_orderID != value)
                {
                    OnorderIDChanging(value);
                    ReportPropertyChanging("orderID");
                    _orderID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("orderID");
                    OnorderIDChanged();
                }
            }
        }
        private global::System.Int32 _orderID;
        partial void OnorderIDChanging(global::System.Int32 value);
        partial void OnorderIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> productID
        {
            get
            {
                return _productID;
            }
            set
            {
                OnproductIDChanging(value);
                ReportPropertyChanging("productID");
                _productID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("productID");
                OnproductIDChanged();
            }
        }
        private Nullable<global::System.Int32> _productID;
        partial void OnproductIDChanging(Nullable<global::System.Int32> value);
        partial void OnproductIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String status
        {
            get
            {
                return _status;
            }
            set
            {
                OnstatusChanging(value);
                ReportPropertyChanging("status");
                _status = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("status");
                OnstatusChanged();
            }
        }
        private global::System.String _status;
        partial void OnstatusChanging(global::System.String value);
        partial void OnstatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> buyUserID
        {
            get
            {
                return _buyUserID;
            }
            set
            {
                OnbuyUserIDChanging(value);
                ReportPropertyChanging("buyUserID");
                _buyUserID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("buyUserID");
                OnbuyUserIDChanged();
            }
        }
        private Nullable<global::System.Int32> _buyUserID;
        partial void OnbuyUserIDChanging(Nullable<global::System.Int32> value);
        partial void OnbuyUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> recommendUserID
        {
            get
            {
                return _recommendUserID;
            }
            set
            {
                OnrecommendUserIDChanging(value);
                ReportPropertyChanging("recommendUserID");
                _recommendUserID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("recommendUserID");
                OnrecommendUserIDChanged();
            }
        }
        private Nullable<global::System.Int32> _recommendUserID;
        partial void OnrecommendUserIDChanging(Nullable<global::System.Int32> value);
        partial void OnrecommendUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> price
        {
            get
            {
                return _price;
            }
            set
            {
                OnpriceChanging(value);
                ReportPropertyChanging("price");
                _price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("price");
                OnpriceChanged();
            }
        }
        private Nullable<global::System.Decimal> _price;
        partial void OnpriceChanging(Nullable<global::System.Decimal> value);
        partial void OnpriceChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="hackthonModel", Name="product")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class product : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new product object.
        /// </summary>
        /// <param name="productID">Initial value of the productID property.</param>
        public static product Createproduct(global::System.Int32 productID)
        {
            product product = new product();
            product.productID = productID;
            return product;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 productID
        {
            get
            {
                return _productID;
            }
            set
            {
                if (_productID != value)
                {
                    OnproductIDChanging(value);
                    ReportPropertyChanging("productID");
                    _productID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("productID");
                    OnproductIDChanged();
                }
            }
        }
        private global::System.Int32 _productID;
        partial void OnproductIDChanging(global::System.Int32 value);
        partial void OnproductIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String url
        {
            get
            {
                return _url;
            }
            set
            {
                OnurlChanging(value);
                ReportPropertyChanging("url");
                _url = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("url");
                OnurlChanged();
            }
        }
        private global::System.String _url;
        partial void OnurlChanging(global::System.String value);
        partial void OnurlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String type
        {
            get
            {
                return _type;
            }
            set
            {
                OntypeChanging(value);
                ReportPropertyChanging("type");
                _type = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("type");
                OntypeChanged();
            }
        }
        private global::System.String _type;
        partial void OntypeChanging(global::System.String value);
        partial void OntypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String country
        {
            get
            {
                return _country;
            }
            set
            {
                OncountryChanging(value);
                ReportPropertyChanging("country");
                _country = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("country");
                OncountryChanged();
            }
        }
        private global::System.String _country;
        partial void OncountryChanging(global::System.String value);
        partial void OncountryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String city
        {
            get
            {
                return _city;
            }
            set
            {
                OncityChanging(value);
                ReportPropertyChanging("city");
                _city = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("city");
                OncityChanged();
            }
        }
        private global::System.String _city;
        partial void OncityChanging(global::System.String value);
        partial void OncityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> rate
        {
            get
            {
                return _rate;
            }
            set
            {
                OnrateChanging(value);
                ReportPropertyChanging("rate");
                _rate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("rate");
                OnrateChanged();
            }
        }
        private Nullable<global::System.Decimal> _rate;
        partial void OnrateChanging(Nullable<global::System.Decimal> value);
        partial void OnrateChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="hackthonModel", Name="user")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class user : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new user object.
        /// </summary>
        /// <param name="userID">Initial value of the userID property.</param>
        public static user Createuser(global::System.Int32 userID)
        {
            user user = new user();
            user.userID = userID;
            return user;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 userID
        {
            get
            {
                return _userID;
            }
            set
            {
                if (_userID != value)
                {
                    OnuserIDChanging(value);
                    ReportPropertyChanging("userID");
                    _userID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("userID");
                    OnuserIDChanged();
                }
            }
        }
        private global::System.Int32 _userID;
        partial void OnuserIDChanging(global::System.Int32 value);
        partial void OnuserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String userName
        {
            get
            {
                return _userName;
            }
            set
            {
                OnuserNameChanging(value);
                ReportPropertyChanging("userName");
                _userName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("userName");
                OnuserNameChanged();
            }
        }
        private global::System.String _userName;
        partial void OnuserNameChanging(global::System.String value);
        partial void OnuserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String password
        {
            get
            {
                return _password;
            }
            set
            {
                OnpasswordChanging(value);
                ReportPropertyChanging("password");
                _password = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("password");
                OnpasswordChanged();
            }
        }
        private global::System.String _password;
        partial void OnpasswordChanging(global::System.String value);
        partial void OnpasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> identity
        {
            get
            {
                return _identity;
            }
            set
            {
                OnidentityChanging(value);
                ReportPropertyChanging("identity");
                _identity = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("identity");
                OnidentityChanged();
            }
        }
        private Nullable<global::System.Int32> _identity;
        partial void OnidentityChanging(Nullable<global::System.Int32> value);
        partial void OnidentityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> credits
        {
            get
            {
                return _credits;
            }
            set
            {
                OncreditsChanging(value);
                ReportPropertyChanging("credits");
                _credits = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("credits");
                OncreditsChanged();
            }
        }
        private Nullable<global::System.Decimal> _credits;
        partial void OncreditsChanging(Nullable<global::System.Decimal> value);
        partial void OncreditsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String phone
        {
            get
            {
                return _phone;
            }
            set
            {
                OnphoneChanging(value);
                ReportPropertyChanging("phone");
                _phone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("phone");
                OnphoneChanged();
            }
        }
        private global::System.String _phone;
        partial void OnphoneChanging(global::System.String value);
        partial void OnphoneChanged();

        #endregion

    
    }

    #endregion

    
}
